### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by buttflattery** [reprovinci/solr-php-client#5]
hi i am using apache slr 4.3.0 and php 5.3.2 and i am receiving fatal error 

here is my code 
function add_solr_index($solr){
    /*
      Create two documents we are using a manual array where as it can be 
      the array returned from a database recordset
    _/
      $docs = array(
        'doc_no2' => array(
          'id' => 12,
          'title' => 'Rana Touqeer',
          'text' => 'Junior Software Engineer',
          'category' => array( 'Engineer','Web Developer'),
        ),  
        /_'doc_no1' => array(
          'id' => 11,
          'title' => 'Omer Aslam',
          'text' => 'Senior Software Engineer',
          'category' => array( 'Engineer', 'Web Developer' ),
        ),

```
    'doc_no3'=>
        array(
           'id' => 13,
          'title' => 'Amjad Shaick',
          'text' => 'Senior Software Engineer',
          'category' => array( 'Engineer', 'Web Developer' )
        )
    */
  );  

  $documents = array();

  foreach ( $docs as $item => $fields ) {

    $part = new Apache_Solr_Document();

    foreach ( $fields as $key => $value ) {
      if ( is_array( $value ) ) {
        foreach ( $value as $data ) {
          $part->setMultiValue( $key, $data );
        }
      }
      else {
        $part->$key = $value;
      }
    }

    $documents[] = $part;
  }
  //
  //
  // Load the documents into the index
  //

  try {
    $solr->addDocuments( $documents );
    $solr->commit();
    echo 'calling optimize';
    $solr->optimize();
    echo 'Record / Document Added';

  }
  catch ( Exception $e ) {
    echo $e->getMessage();
  }
```

   } 

( ! ) Fatal error: Class 'Apache_Solr_Compatibility_Solr3CompatibilityLayer' not found in D:\xampp\htdocs\solr-php\Solr-master\Service.php on line 261
Call Stack
# Time    Memory  Function    Location

1   0.0004  354600  {main}( )   ..\solr.php:0
2   0.0020  582336  Apache_Solr_Service->__construct( ) ..\solr.php:4

**Comment by rjkip** [comment]
Hi,

This library uses Composer for automatically loading all the necessary classes. You can [read up on Composer here](http://getcomposer.org/doc/00-intro.md). If you do not wish to use Composer, you must include all the necessary classes by yourself.

Good luck!

**Comment by nidhia-cuelogic** [comment]
still facing same error...
