### ISSUE TITLE
Add methods removed attributes

### ISSUE THREAD

**Issue by GZyl** [reprovinci/solr-php-client#7]
Attributes for "add" 
- allowDups 
- overwritePending 
- overwriteCommitted

are removed in Solr4.0 - use "overwrite"

**Comment by rjkip** [comment]
I'll look into this asap.

**Comment by rjkip** [comment]
To preserve the current API, would you agree `overwrite` is `true` when `allowDups` is `false` and `overwritePending` and `overwriteCommitted` are `true`?

It would seem adding `overwrite="true/false"` to [`<add />`](https://github.com/reprovinci/solr-php-client/blob/master/Apache/Solr/Service.php#L754-L756) would solve this issue. It should break neither < 4.0, nor >= 4.0.

**Comment by GZyl** [comment]
**overwritePending** and **overwriteCommitted** default are negation of **allowDups** in Solr <4.0.

In Solr >= 4.0
**overwrite** - default is "true", meaning newer documents will replace previously added documents with the same uniqueKey.

For me **overwrite** = !**allowDups** 

It should be connected with **Apache_Solr_Compatibility_Solr4CompatibilityLayer**

**Comment by rjkip** [comment]
Ok, `overwrite=!allowDups`.

I think we should move all XML generation into the comp layer and tag v2.0.0, as it would be a BC break. If you require these changes soon or if you feel up to it, you can send me a PR. Otherwise I may look into it this weekend.

**Comment by GZyl** [comment]
My first PR ( https://github.com/reprovinci/solr-php-client/pull/8 ) on github ;]
Tested on PHP 5.5.10 (PHPUnit 3.7.32) is OK.
